version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
